apiVersion: v1
kind: ConfigMap
metadata:
  name: shubham-cm
data:
  resource.exclusions: |
    - apiGroups:
      - cilium.io/v2
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  application.resourceTrackingMethod: annotation